services:
  ip-monitor:
    build: .
    container_name: ip-monitor
    restart: unless-stopped
    ports:
      - "8081:8080"  # Web dashboard at http://localhost:8081
    volumes:
      - ./logs:/var/log:rw
      - ./data:/app/data:rw  # Persistent configuration storage
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
      - WEB_PORT=8080
      
      # Configuration Mode: Choose ONE approach
      # Option 1: Environment Variables (traditional)
      # Uncomment these for environment-based configuration
      # - SAFE_IP_RANGE=192.168.1.0/24
      # - WEBHOOK_URL=http://homeassistant.local:8123/api/webhook/your-webhook-id
      # - WEBHOOK_METHOD=POST
      # - WEBHOOK_USER=
      # - WEBHOOK_PASS=
      # - CHECK_INTERVAL=12h
      # - ALERT_COOLDOWN=1h
      
      # Option 2: File-based Configuration (recommended)
      # Leave environment variables commented out to enable web configuration
      # Settings will be stored in ./data/config.json
      
      # CRON Configuration (always required)
      # Format: "minute hour day month weekday"
      # Examples:
      #   "0 */12 * * *"     - Every 12 hours (default)
      #   "0 */6 * * *"      - Every 6 hours  
      #   "*/30 * * * *"     - Every 30 minutes
      #   "0 9,21 * * *"     - At 9 AM and 9 PM daily
      #   "0 */2 * * *"      - Every 2 hours
      #   "0 0 * * *"        - Once daily at midnight
      
      - CRON_SCHEDULE=0 */12 * * *     # Every 12 hours
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"